
-- SENARYO 5

--1
SELECT
TITLE+' ('+CONVERT(VARCHAR,YEAR(RELEASE_DATE))+')' TITLE_,
RELEASE_DATE,

CONVERT(VARCHAR,RUNTIME/60)+'h '+CONVERT(VARCHAR,RUNTIME%60)+'m' DURATION,
VOTE_AVERAGE*10 VOTE_AVERAGE,TAGLINE,OVERVIEW,POSTER_PATH,
(
SELECT GENRE+',' FROM MOVIE_GENRE MG
INNER JOIN GENRE G ON G.GENREID=MG.GENREID
WHERE MG.FILMID=M.FILMID
FOR XML PATH('')
) GENRES,
(
SELECT(P.NAME_+' ('+J.JOB+')')+',' FROM CREW_CREDIT CC
INNER JOIN DEPARTMENT D ON D.ID=CC.DEPARTMENTID
INNER JOIN JOB J ON  J.ID=CC.JOBID
INNER JOIN PERSON P ON P.PERSONID=CC.PERSONID

WHERE FILMID=M.FILMID AND j.JOB IN ('Director','Screenplay')
FOR XML PATH('')
) CREW

FROM MOVIE M
WHERE FILMID=98

--2
--film genel bilgi
SELECT
TITLE, YEAR(RELEASE_DATE) AS YEAR_,RELEASE_DATE,
CONVERT(VARCHAR,RUNTIME/60)+'h '+CONVERT(VARCHAR,RUNTIME%60)+'m' DURATION,
VOTE_AVERAGE*10,TAGLINE,OVERVIEW

FROM MOVIE
WHERE TITLE LIKE 'Gladiator' AND FILMID=98
--yonetmen ve senaristler
SELECT M.TITLE,P.NAME_,D.DEPARTMENT,J.JOB FROM CREW_CREDIT CC
INNER JOIN MOVIE M ON M.FILMID=CC.FILMID
INNER JOIN PERSON P ON P.PERSONID=CC.PERSONID
INNER JOIN DEPARTMENT D ON D.ID=CC.DEPARTMENTID
INNER JOIN JOB J ON J.ID=CC.JOBID

WHERE M.FILMID=98
AND J.JOB IN ('Director','Screenplay')

--OYUNCULAR
SELECT M.TITLE, P.NAME_,P.PROFILE_PATH, CC.CHARACTER_,CC.ORDER_ FROM CAST_CREDIT CC
INNER JOIN MOVIE M ON M.FILMID=CC.FILMID
INNER JOIN PERSON P ON P.PERSONID=CC.PERSONID
WHERE M.FILMID=98
ORDER BY ORDER_

--ANAHTAR KELIMELER VE ETIKETLER
SELECT M.TITLE,MK.KEYWORD FROM MOVIE_KEYWORD MK
INNER JOIN MOVIE M ON M.FILMID=MK.FILMID
WHERE MK.FILMID=98

--YORUMLAR
SELECT M.TITLE, MR.* FROM MOVIE_REVIEW MR
INNER JOIN MOVIE M ON M.FILMID=MR.FILMID
WHERE M.FILMID=98