-- SENARYO 3

-- SALEORDERS Tablosu Uzerinde hangi sehirde ne kadarlik satis yapildigi bilgisini ceken sql sorgusunu yaziniz.

SELECT CITY,  SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS
GROUP BY CITY
ORDER BY CITY


-- SALEORDERS Tablosu Sehirlere göre hangi ayda ne kadarlÝk satýS yapildiði bilgisini ceken sql sorgusunu yaziniz.

SELECT CITY, MONTH_, SUM(LINETOTAL) AS TOTALSALE 
FROM SALEORDERS
GROUP BY CITY, MONTH_
ORDER BY CITY,MONTH_


-- Her ilin haftanin en çok hangi gününde satýs yaptiðini ogrenip ona gore þehir ve gunlere ozel kampanya yapmak istiyoruz. 
-- Sehirlerin haftanin günlerine göre ne kadarlik satýs yaptiði bilgisini sekildeki gibi getiren sorguyu yaziniz.

SELECT CITY, DAYOFWEEK_, SUM(LINETOTAL) AS TOTALSALE 
FROM SALEORDERS
GROUP BY CITY, DAYOFWEEK_
ORDER BY CITY,DAYOFWEEK_


UPDATE SALEORDERS SET DAYOFWEEK_='Pazartesi' WHERE DAYOFWEEK_ = '01.PZT'
UPDATE SALEORDERS SET DAYOFWEEK_='Salý' WHERE DAYOFWEEK_ = '02.SAL'
UPDATE SALEORDERS SET DAYOFWEEK_='Çarþamba' WHERE DAYOFWEEK_ = '03.ÇAR'
UPDATE SALEORDERS SET DAYOFWEEK_='Perþembe' WHERE DAYOFWEEK_ = '04.PER'
UPDATE SALEORDERS SET DAYOFWEEK_='Cuma' WHERE DAYOFWEEK_ = '05.CUM'
UPDATE SALEORDERS SET DAYOFWEEK_='Cumartesi' WHERE DAYOFWEEK_ = '06.CMT'
UPDATE SALEORDERS SET DAYOFWEEK_='Pazar' WHERE DAYOFWEEK_ = '07.PAZ'





-- Her ilin haftanin en cok hangi gununde satis yaptýðýný ögrenip ona gore sehir ve gunlere ozel kampanya yapmak istiyoruz. 
-- Sehirlerin haftanin gunlerine gore ne kadarlik satýs yaptiði bilgisini sekildeki gibi getiren sorguyu yaziniz.

SELECT 
DISTINCT CITY,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='Pazartesi') AS PAZARTESÝ,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='Salý') AS SALI,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='Çarþamba') AS ÇARÞAMBA,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='Perþembe') AS PERÞEMBE,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='Cuma') AS CUMA,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='Cumartesi') AS CUMARTESÝ,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='Pazar') AS PAZAR

FROM SALEORDERS S
ORDER BY 1




-- Her ilin en cok satan ilk 5 kategorisini sekildeki gibi getiren sorguyu yaziniz.

SELECT 
S.CITY, S1.CATEGORY1, SUM(S1.TOTALSALE) AS TOTALSALE
FROM SALEORDERS S
CROSS APPLY (SELECT TOP 5 CATEGORY1, SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS WHERE CITY=S.CITY GROUP BY CATEGORY1 ORDER BY 2 DESC) S1

GROUP BY S.CITY, S1.CATEGORY1
ORDER BY S.CITY, SUM(S1.TOTALSALE) DESC





-- Her sehirde en çok satis yapilan 3 kategoriyi ve onun altinda en cok satýs yapilan 3 alt kategoriyi sekildeki gibi getiren sorguyu yaziniz.

SELECT  S.CITY, S1.CATEGORY1,S2.CATEGORY2, SUM(S1.TOTALSALE) 
FROM SALEORDERS S
CROSS APPLY (SELECT TOP 3 CATEGORY1, SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS WHERE CITY=S.CITY GROUP BY CATEGORY1 ORDER BY 2 DESC) S1
CROSS APPLY (SELECT TOP 3 CATEGORY2, SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS WHERE CITY=S.CITY AND CATEGORY1=S1.CATEGORY1 GROUP BY CATEGORY2 ORDER BY 2 DESC) S2

GROUP BY CITY, S1.CATEGORY1, S2.CATEGORY2
ORDER BY 1,2,4 DESC



-- Tablolarý Join ile birleþtirerek SALEORDERS tablosunu doldurunuz.
  
  SELECT 
  OD.ID,
  U.USERNAME_,U.NAMESURNAME,U.TELNR1,U.TELNR2,
  C.COUNTRY,CT.CITY,T.TOWN,ADR.ADDRESSTEXT,
  O.ID AS ORDERID, ITM.ITEMCODE, ITM.ITEMNAME,ITM.BRAND,ITM.CATEGORY1,
  ITM.CATEGORY2,ITM.CATEGORY3,ITM.CATEGORY4,
  OD.AMOUNT,OD.UNITPRICE,OD.LINETOTAL, CONVERT(DATE,O.DATE_) AS ORDERDATE, CONVERT(time,o.DATE_) ORDERTIME,
  YEAR(O.DATE_) AS YEAR_, DATENAME(MONTH,O.DATE_) AS MONTH_, DATENAME(DW,O.DATE_) AS DAYOFWEEK_

  FROM ORDERS O
  INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
  INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
  INNER JOIN USERS U ON U.ID = O.USERID
  INNER JOIN ADDRESS ADR ON ADR.ID = O.ADDRESSID
  INNER JOIN COUNTRIES C ON C.ID = ADR.COUNTRYID
  INNER JOIN CITIES CT ON CT.ID = ADR.CITYID
  INNER JOIN TOWNS T ON T.ID = ADR.TOWNID


-- Iliskisel tablolari kullanarak hangi sehirde ne kadarlik satis yapildigi bilgisini getiren sorguyu yaziniz.

SELECT 
CT.CITY,  SUM(O.TOTALPRICE) AS TOTALPRICE
FROM ORDERS O
INNER JOIN ADDRESS ADR ON ADR.ID = O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID = ADR.CITYID
GROUP BY CT.CITY

-- Her markanin ana kategoriye gore en çok satan CATEGORY1 alanini Sekildeki gibi getiren sorguyu yaziniz.

SELECT 
ITM.BRAND,ITM.CATEGORY1, SUM(OD.LINETOTAL) AS TOTALPRICE
FROM ORDERDETAILS OD
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
GROUP BY ITM.BRAND, ITM.CATEGORY1




-- Her kategorinin icerisinde en çok satan markayi sekildeki gibi getiren sorguyu yaziniz.

SELECT 
ITM.CATEGORY1, ITM.BRAND, SUM(OD.LINETOTAL) AS TOTALPRICE
FROM ORDERDETAILS OD
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
GROUP BY ITM.CATEGORY1,ITM.BRAND
ORDER BY ITM.CATEGORY1, SUM(OD.LINETOTAL) DESC




-- Her bir UrUn zaman icinde farkli fiyatlar ile satilmaktadir. 
-- Her Urunun minimum, maxium ve ortalama ne kadar fiyattan satildigi bilgisi ile kaç kez ve kaç adet satildiði bilgisini sekildeki gibi getiren sorguyu yaziniz.

SELECT 
ITM.BRAND, ITM.CATEGORY1, ITM.ITEMCODE,ITM.ITEMNAME,COUNT(OD.ID) AS SALECOUNT,
SUM(OD.AMOUNT) AS TOTALMOUNT,
MIN(OD.UNITPRICE) AS MINPRICE, MAX(OD.UNITPRICE) AS MAXPRICE,
AVG(OD.UNITPRICE) AS AVGPRICE
FROM ITEMS ITM
INNER JOIN ORDERDETAILS OD ON OD.ITEMID = ITM.ID
GROUP BY ITM.BRAND, ITM.CATEGORY1, ITM.ITEMCODE,ITM.ITEMNAME




--Muþterilerin sistemde kayitli adres sayisini ve son alýþveris yaptiði adres bilgisini sekildeki gibi getiren sorguyu yaziniz.

SELECT U.ID, U.NAMESURNAME,
(SELECT COUNT(*) FROM ADDRESS WHERE USERID = U.ID) AS ADDRESSCOUNT,
(SELECT ADDRESSTEXT FROM ADDRESS WHERE ID IN 
                  (SELECT TOP 1 ADDRESSID FROM ORDERS WHERE USERID = U.ID ORDER BY DATE_ DESC)
 ) AS LASTADDRESS
FROM USERS U




-- Musterilerin sistemde kayitli adres sayisini ve son alisveris yaptigi adres bilgisini sehir, ilce ve semti ile birlikte sekildeki gibi getiren sorguyu yaziniz.

SELECT TMP.NAMESURNAME, TMP.ADDRESSCOUNT,C.CITY,T.TOWN,D.DISTRICT,A.POSTALCODE,
A.ADDRESSTEXT FROM
(
SELECT U.ID, U.NAMESURNAME,
(SELECT COUNT(*) FROM ADDRESS WHERE USERID = U.ID) AS ADDRESSCOUNT,
(SELECT TOP 1 ADDRESSID FROM ORDERS WHERE USERID = U.ID ORDER BY DATE_ DESC) AS LASTADDRESSID
FROM USERS U) TMP
INNER JOIN ADDRESS A ON A.ID = TMP.LASTADDRESSID
INNER JOIN CITIES C ON C.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID




-- Ocak ayý icerisinde en az 10 gun boyunca gunluk 500 TL ve altinda siparis veren sehirleri sekildeki gibi listelettiren sorguyu yaziniz.

SELECT CITY, COUNT(*) AS BESYUZTL_ALTI_CIRO_YAPILAN_GUN   FROM
(
SELECT 
C.CITY,CONVERT(DATE,O.DATE_) AS DATE_,
SUM(O.TOTALPRICE) AS TOTALPRICE
FROM ORDERS O
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN CITIES C ON C.ID = A.CITYID
WHERE O.DATE_ BETWEEN '20190101' AND '2019-01-31 23:59:59'
GROUP BY C.CITY , CONVERT(DATE,O.DATE_)
HAVING SUM(O.TOTALPRICE)<500
)TMP
GROUP BY CITY







